Temperature Sensor Driver
queens-satellite-team/obc_current pull request #1
Opened 2023-10-31 15:54 UTC by hana-t

2023-11-19 02:00 UTC, c-ola requested changes
Looks good, just needs some small organizational changes i think.

2023-11-19 02:00 UTC, c-ola commented on drivers/TempSensor.h
Needs to  `#include <cstdint>` if you want to use the types `uint8_t` and `uint16_t` (I was getting errors trying to compile).

2023-11-19 02:00 UTC, c-ola commented on drivers/TempSensor.cpp
Shouldn't have a main method, could move it to usage.cpp as a main method.

2023-11-19 02:00 UTC, c-ola commented on drivers/usage.cpp
This file is old? (no `ambientTemp()` method in TempSensor)

2023-11-19 02:00 UTC, c-ola commented on drivers/CMakeLists.txt
You can have something like
```
add_executable(testTempSensor usage.cpp TempSensor.cpp)
target_link_libraries(testTempSensor i2c)
target_include_directories(testTempSensor PUBLIC .)
```
in the CMakeLists.txt for the tempsensor driver directory (also put the tempsensor files in its own directory.

The CMakeLists.txt should also add tempsensor.cpp  as a source to the main project target.
```
target_sources(${PROJECT_NAME} PUBLIC TempSensor.cpp)
target_include directories(${PROJECT_NAME} PUBLIC .)
``` 

Finally in the drivers CMakeLists.txt you just `add_subdirectory(tempsensor)`

2023-11-19 02:31 UTC, JaxHodg commented on drivers/TempSensor.h
Fixed, not sure why mine didn't error out

2023-11-19 02:32 UTC, JaxHodg commented on drivers/TempSensor.cpp
Removed. That was previously used for testing

2023-11-19 02:32 UTC, JaxHodg commented on drivers/usage.cpp
Removed. That was previously used for testing

2023-11-19 02:33 UTC, JaxHodg commented on drivers/CMakeLists.txt
Tbh I don't really understand cmake files, but the test should use `tests/Temperature_Sensor/test_TempSensor.cpp` not `usage.cpp`.

I've written `run_test.sh` just to get it quickly working

2024-01-28 00:05 UTC, c-ola approved these changes
looks good

2024-03-02 17:13 UTC, HarrisonMKG approved these changes
LGTM

2024-03-02 20:35 UTC, merged